name: Glifcos-p
main: glifcos\glifcos
version: 0.1.1
api: [2.0.0, 1.0.0]
author: HotFireyDeath\Chopstick Software

commands:
    glifcos:
        description: Glifcos main command.
        usage: /glifcos
        permission: glifcos.main